project:
  type: book

book:
  title: "aa"
  author: "Norah Jones"
  date: "12/22/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
csl: APA.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



